import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseHTML } from 'linkedom';
import { type NoteFile, readAllNotes } from '../store/reader.js';
import { getConfig } from '../util/config.js';

export interface BacklinkEntry {
  from: string; // source note id
  to: string; // target note id
  type: string; // mentions | refines | contradicts | …
  auto: boolean; // generated by auto-linker?
  surface?: string; // visible link text
  confidence: 'extracted' | 'inferred' | 'ambiguous';
  confidenceScore: number;
}

export interface BacklinksIndex {
  outgoing: Record<string, BacklinkEntry[]>; // id -> outgoing edges
  incoming: Record<string, BacklinkEntry[]>; // id -> incoming edges
  generated: string; // ISO timestamp
  total_edges: number;
}

const BACKLINKS_FILENAME = 'backlinks.json';

export function buildBacklinks(notes?: NoteFile[]): BacklinksIndex {
  const all = notes ?? readAllNotes();
  const outgoing: Record<string, BacklinkEntry[]> = {};
  const incoming: Record<string, BacklinkEntry[]> = {};
  let total = 0;

  for (const note of all) {
    if (!note.id) continue;
    const { document } = parseHTML(`<!doctype html><html><body>${note.html}</body></html>`);
    const root = document.body || document.documentElement;
    if (!root) continue;
    const anchors = Array.from(root.querySelectorAll('a[href]'));
    for (const a of anchors) {
      const href = a.getAttribute('href') ?? '';
      const targetId = parseTargetId(href);
      if (!targetId || targetId === note.id) continue;
      const autoFlag = a.getAttribute('data-cerveau-link-auto') === '1';
      const confAttr = a.getAttribute('data-cerveau-link-confidence') as 'extracted' | 'inferred' | 'ambiguous' | null;
      const confidence = confAttr ?? (autoFlag ? 'inferred' : 'extracted');
      const confidenceScore = confidence === 'extracted' ? 1.0 : confidence === 'inferred' ? 0.5 : 0.2;
      const entry: BacklinkEntry = {
        from: note.id,
        to: targetId,
        type: a.getAttribute('data-cerveau-link-type') ?? 'link',
        auto: autoFlag,
        surface: (a.textContent ?? '').trim().slice(0, 120) || undefined,
        confidence,
        confidenceScore,
      };
      (outgoing[note.id] ??= []).push(entry);
      (incoming[targetId] ??= []).push(entry);
      total += 1;
    }
  }

  return {
    outgoing,
    incoming,
    generated: new Date().toISOString(),
    total_edges: total,
  };
}

export function saveBacklinks(idx: BacklinksIndex): string {
  const cfg = getConfig();
  if (!existsSync(cfg.cachePath)) mkdirSync(cfg.cachePath, { recursive: true });
  const path = join(cfg.cachePath, BACKLINKS_FILENAME);
  writeFileSync(path, JSON.stringify(idx, null, 2), 'utf8');
  return path;
}

export function loadBacklinks(): BacklinksIndex | null {
  const cfg = getConfig();
  const path = join(cfg.cachePath, BACKLINKS_FILENAME);
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as BacklinksIndex;
  } catch {
    return null;
  }
}

function parseTargetId(href: string): string | null {
  // Accept: #/note/id format used by knowledge-nodes
  const noteMatch = href.match(/^#\/note\/([a-z0-9_-]+)$/i);
  if (noteMatch) return noteMatch[1];

  // Accept: #id, ../path.html#id, ./path.html#id, path.html
  const hashIdx = href.indexOf('#');
  if (hashIdx >= 0) {
    const after = href.slice(hashIdx + 1).trim();
    if (after && /^[a-z0-9_-]+$/i.test(after)) return after;
  }
  // Fallback: derive id from filename
  const fileMatch = href.match(/([^/\\]+)\.html?(?:[#?].*)?$/i);
  if (fileMatch) {
    return fileMatch[1].toLowerCase();
  }
  return null;
}
